location="centralus"
rg-prefix="rg-multienv"
rg-name="rg-multienv-dev"
storage-account-name="pirladev"
index_document="index.html"
source_content="<h1>This is static content coming from the Dev Terraform</h1>"
