location="centralus"
rg-prefix="rg-multienv"
rg-name="rg-multienv-qa"
storage-account-name="pirlaqa"
index_document="index.html"
source_content="<h1>This is static content coming from the QA Terraform</h1>"
