location="centralus"
rg-prefix="rg-multienv"
rg-name="rg-multienv-prod"
storage-account-name="pirlaprod"
index_document="index.html"
source_content="<h1>This is static content coming from the Production Terraform</h1>"
